language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-4.9-dev
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
install:
- npm ci
- gem install travis
before_script: npm ls --production >/dev/null
after_success: npm run coverage:report
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - secure: D3DIiFQtRDlPfXGeXs69V2oKhUptEGHJrf23NwX9iYVUkBgENexyoHcOmW7oigMft44QpebFC8EPZdkOke8YssrUXqDLk6dWJIHQM3+7zpAdk+cNnOTZdg1XrBTfBJwIAiCuWZcEw3RbonYFxfTFP3mM/xcqegkohujX0QGhm2zwCviBqzWWd3vk7IJPIHwKgDHTMZdBYWVclNv6h/0tiBDZdv/RW/Gn0pYIUuCDdhyRrPDyoHltYG1ja9ya9JF4j9WGRnremkzhfhkzB9OyWwvfj1bvlVjPiappuzD9/Ka9FvNK9RYm2BOnNDHmg/zkfFP4bdMDG7jKfYFSeWOFie3oNHRLu098ER4ou20/iL3iWB42lkRLlA2HYbPV8w87rggEwScJicVA84lcqvYF+svtYzbAL4om+IIab94hAlYmToC8uG1GmwliMG09ibEcpOpbXpslOwCIVk/QGfaddrbjkg/LMyK4WZAI21Hc/OtGLBdsH7l7/gMAkezvpjzdmQiHRaJrlwtGfSoivXWj6l4kt+qg/IUKvhickkb/fVGalims+iExbeFC+g5TgeJ4rd/CNpqEg9gMVdmWM36moh8zZe0zrN/xXJp0VB5Jiy0TZ9brcNiDEnFdSPy6wXgtZTAtpd8rT+FUxIUa77hF6GOZwHZPOO2ImOQrBoAdR24=
  - secure: xrkm9zXRopYZzjcS8JJnGuh9y+R59Gpa1/c8YQXuel8DqYT9jvOKPA/i+/aXVgVIbCZcCkWHLiJRSnEj728LQljXJQTcG+uyc+mWBAli/bWPS7qiJGtUdeDoSXrsGyLpt/W2sh65+pY5uXOdqEBNuLEYsU5Pao9TYGOGzQPJPqVovmOz7wXi37BvNWrNJ46EcqS/RG8Rmjr8/oSAGkHTy8lPKskfVDvl9zu1RgDD0CbwxFsxboDGstEnVgwU7z1ifdZBJ40wlhHdyjkqrZhCcfb5CC1YJIpWtIMqddjRfifeutyLzTuwceloppCi6qcVW4qKZA5UlN0ZP8Vtfvf/V0L0GdKSKbCklyLWl+lCS727vrJXuiAz78fQFex0RH+n0iq5/Xs7hV/SD8SocArZmi+BDV2tL5ZASXuWu0Paj/87BhyEBQy1HF+ZyUV0I7/tyBPw0FWTqJfBcamwJzkOYwyF+NOOACRfLS0nyxC4jifrFKsWcApdPWfWiQWa6CjSZ53h6zpCJ5CtRjk2HaASZsIwH+10ULbPxmXoe9rRnnnAPLLERtb+XdJUx6x6dyPy1I7tlHNyxs+jYKfp60DCp++AIxatJCdrEJAJ+TNq01MVlW4YPfI39iwOmFxKn7v85WoNKHKrv3xssTpY4Ejac3wbR3Luim2B7mydS6kufJo=
